server:
  port: 3000

spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${db.host}:${db.port}:XE
    username: ${db.username}
    password: ${db.password}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: create

  devtools:
    livereload:
      enabled: true

  web:
    resources:
      staticLocations: file:src/main/resources/static/

  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 60MB
      fileSizeThreshold: 30MB


file:
  upload:
    path: D:/uploads
    url: /upload/

logging:
  level:
    org.hibernate.type: info
    org.hibernate.orm.jdbc.bind: trace